# default result code
RESULT_UNKNOWN = -127
RESULT_IS_NONE = -126
RESULT_OVER_DEADLINE = -125
RESULT_OVER_FINISHTIME = -124
SEND_FAIL = -4
DESERIALIZE_FAIL = -3
SERIALIZE_FAIL = -2
RESULT_ERROR = -1
RESULT_SUCCESS = 0
# result over 0 is customer error

MAX_URI_LEN = 8192

TOKENNAME = 'Auth-Token'
ADMINAPI = 'ADMINAPI'
